import { memo } from 'react';
import { BreadCell, SpecialItemType, isSpecialItem } from '../models/BreadCell';
import { BREAD_DATA } from '../models/BreadType';
import styles from './BreadCellView.module.css';

// Power-up cells generated by matching 4/5/6+ breads. Visually presented as
// "bombs" — the badge + colored glow + pulse animation makes them read as
// explosive items, not just another bread.
const SPECIAL_ITEM_INFO: Record<
  SpecialItemType,
  { image: string; name: string; color: string; badge: string }
> = {
  [SpecialItemType.None]:   { image: '', name: '', color: '', badge: '' },
  [SpecialItemType.Matcha]: {
    image: '/brandings/cube-matcha-cream.png',
    name: 'Cross Bomb',
    color: '#76c673',
    badge: '✚',   // cross pattern hint
  },
  [SpecialItemType.Choco]:  {
    image: '/brandings/cube-choco-cream.png',
    name: 'Block Bomb',
    color: '#a35530',
    badge: '◼',   // 3x3 block
  },
  [SpecialItemType.MilkTea]: {
    image: '/breads/milktea.png',
    name: 'Mega Bomb',
    color: '#ffb84d',
    badge: '✦',   // big-bang star
  },
};

interface Props {
  cell: BreadCell;
  isSelected: boolean;
  isMatched: boolean;
  isDragging: boolean;
  isDropTarget: boolean;
  cellSize: number;
  dragOffset: { x: number; y: number } | null;
  onTap: () => void;
  onDragStart: (e: React.PointerEvent) => void;
}

export default memo(function BreadCellView({
  cell,
  isSelected,
  isMatched,
  isDragging,
  isDropTarget,
  cellSize,
  dragOffset,
  onTap,
  onDragStart,
}: Props) {
  const breadInfo = BREAD_DATA[cell.breadType];
  const isSpecial = isSpecialItem(cell);
  const specialInfo = isSpecial ? SPECIAL_ITEM_INFO[cell.specialType] : null;

  const className = [
    styles.cell,
    isSelected ? styles.selected : '',
    isMatched ? styles.matched : '',
    isDragging ? styles.dragging : '',
    isDropTarget ? styles.dropTarget : '',
    isSpecial ? styles.special : '',
    isSpecial && cell.specialType === SpecialItemType.Matcha ? styles.specialMatcha : '',
    isSpecial && cell.specialType === SpecialItemType.Choco ? styles.specialChoco : '',
    isSpecial && cell.specialType === SpecialItemType.MilkTea ? styles.specialMilkTea : '',
  ].filter(Boolean).join(' ');

  const style: React.CSSProperties = {
    width: cellSize,
    height: cellSize,
    backgroundColor: isSpecial && specialInfo ? specialInfo.color : breadInfo.color,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 8,
    flexShrink: 0,
  };

  if (isDragging && dragOffset) {
    style.transform = `translate(${dragOffset.x}px, ${dragOffset.y}px) scale(1.15)`;
    style.zIndex = 100;
  }

  const imageSrc = isSpecial && specialInfo ? specialInfo.image : breadInfo.image;
  const imageAlt = isSpecial && specialInfo ? specialInfo.name : breadInfo.name;

  // Stagger the idle float animation so cells don't bob in unison.
  // Hash the board position into a negative animation-delay (0 to 2.6s).
  const phaseOffset = ((cell.row * 7 + cell.col * 13) % 26) / 10;

  return (
    <div
      className={className}
      style={style}
      onClick={onTap}
      onPointerDown={onDragStart}
    >
      <img
        src={imageSrc}
        alt={imageAlt}
        className={styles.icon}
        style={{
          width: cellSize * 0.85,
          height: cellSize * 0.85,
          objectFit: 'contain',
          animationDelay: `-${phaseOffset}s`,
        }}
        draggable={false}
      />
      {isSpecial && specialInfo && (
        <span
          className={styles.bombBadge}
          style={{ fontSize: cellSize * 0.32 }}
        >
          {specialInfo.badge}
        </span>
      )}
    </div>
  );
});
